### ISSUE TITLE
evaluation error

### ISSUE THREAD

**Issue by DongJT1996** [leonid-pishchulin/poseval#8]
Hi,
I just want to try the function evaluation.py to get the result. So i use the the annotations of train and val set, e.g. 000001_bonn_relpath_5sec_trainsub.mat to get the json file using mat2json.m function. Then I use the json file as prediction and groundtruth, and use the following command to test:

python evaluate.py   --groundTruth=/mnt/data/dataset/posetrack/posetrack_data/annotations/myval/   --predictions=/mnt/data/dataset/posetrack/posetrack_data/annotations/predictions/   --evalPoseEstimation

however, there is an error as following:
![image](https://user-images.githubusercontent.com/25705996/39658558-b5a0a9fa-5048-11e8-99cd-949e151548a3.png)
Do you have any ideas? thank you!

**Comment by leonid-pishchulin** [comment]
please try to pull from the mainline and see if error got fixed. I pushed an [update](https://github.com/leonid-pishchulin/poseval/commit/60cd97e9282c1c0fb98351bc82718be8702c50a2) yesterday that might have fixed your issue as well.

**Comment by ktr-hubrt** [comment]
this error still exists，which comes from data preparation (for every point required json does not score
![1](https://user-images.githubusercontent.com/32117005/41019890-393e8cf6-6993-11e8-9e88-a541f34e0055.png)
,however when testing ,the code require every point's score
